version: '3'

networks:
    zk:
        driver: bridge

services:
    zk0:
        image: zookeeper:3.4.12
        restart: always
        container_name: zk0
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
        networks:
            - zk
    zk1:
        image: zookeeper:3.4.12
        restart: always
        container_name: zk1
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
        networks:
            - zk
    zk2:
        image: zookeeper:3.4.12
        restart: always
        container_name: zk2
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
        networks:
            - zk
