global: # 全局变量
    scrape_interval: 3s       # 访问目标间隔
    evaluation_interval: 15s   # 访问规则文件 更新的间隔

rule_files: # 报警规则文件
    - 'rules/*.yml'

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets:
                  - '192.168.56.100:9093'

scrape_configs:
    - job_name: 'nginx_demo'
      #static_configs:  # 静态配置
          #- targets: ['192.168.56.100:9100']

      file_sd_configs:  # 动态配置
        - files:
          - /etc/prometheus/nginx.yml
          refresh_interval: 1m
      metrics_path: "/metrics" # 默认数据采集路径

