version: '3'

networks:
    elastic:
        driver: bridge

services:
    es1:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
        container_name: es1
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1,es2,es3"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        #volumes:
            #- data01:/usr/share/elasticsearch/data
        hostname: es1
        ports:
            - 9200:9200
        networks:
            - elastic
    es2:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
        container_name: es2
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1,es2,es3"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        hostname: es2
        networks:
            - elastic
    es3:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
        container_name: es3
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1,es2,es3"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        hostname: es3
        networks:
            - elastic

