version: "3"

services:
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        ports:
            - "5601:5601"
        networks:
            - "elk-net"
        volumes:
            - ./kibana.yml:/etc/kibana/kibana.yml

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
        networks:
            - "elk-net"

    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.1
        container_name: logstash
        #- type: bind
          #source: "./logstash/logstash_stdout.conf"
          #target: "/usr/share/logstash/pipeline/logstash.conf"
        networks:
            - "elk-net"

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.10.1
        container_name: filebeat
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /root/go-frame/:/workspace
        networks:
            - "elk-net"
networks:
    elk-net:
