version: "3"

networks:
    my-docker-net:

services:
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        ports:
            - "5601:5601"
        networks:
            - "my-docker-net"
        volumes:
            - ./kibana.yml:/etc/kibana/kibana.yml

    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.1
        container_name: logstash
        #- type: bind
          #source: "./logstash/logstash_stdout.conf"
          #target: "/usr/share/logstash/pipeline/logstash.conf"
        networks:
            - "my-docker-net"

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.10.1
        container_name: filebeat
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /root/go-frame/:/workspace
        networks:
            - "my-docker-net"
