global:
    resolve_timeout: 1m
    smtp_from: example@demo.com
    smtp_smarthost: smtp.example.org:587
    smtp_auth_username: example@demo.com
    smtp_auth_password: password
    smtp_require_tls: false   # 协议是否使用tls 需要注意默认是 true

route:
    receiver: 'default-receiver'
    repeat_interval: 1m

receivers:
    - name: 'default-receiver'
      email_configs:
          - to: demo@qq.com
